backend:
  name: git-gateway
  repo: Novartus/nextjs-cms-blog
  branch: main

media_folder: public/img
public_folder: img
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Data"
        name: "data"
        widget: list
        fields:
          - {
              label: "Title / Name",
              name: "name",
              widget: "text",
              required: true,
            }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: true,
            }
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - {
                  label: "Name",
                  name: "name",
                  widget: "string",
                  required: true,
                }
              - {
                  label: "Description",
                  name: "description",
                  widget: "text",
                  required: true,
                }
